name: 'GetLast Pr Details'
description: 'Enable Version Increment based on last PR details'
inputs:
  token:
    description: 'The token to be used to interact with github api'
    required: true
  reponame:
    description: 'The name of the repository'
    required: true
  commitMessage:
    description: 'The last commit message of the merged pr'
    required: true    
  eventName:
    description: 'The github event which triggered this action'
    required: true        
outputs:
  PR_BRANCH:
    description: 'The branch name of the last PR'
  AutoIncrement:
    description: 'Indicates whether to auto-increment the version'    
runs:
  using: 'node20'
  main: 'index.js'